#Your build pipeline references an undefined variable named ‘BUILDCONFIGURATION’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘BUILDPLATFORM’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rr)

trigger:
- main

variables:
  ArtifactName: 'NXT3Shift_Artifacts'
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Debug'

steps:
- task: PackageES.pkges-vpack-task.pkges-vpack-task.PkgESVPack@12
  displayName: 'PkgESVPack '
  inputs:
    sourceDirectory: '$(Build.ArtifactStagingDirectory)'
    description: '$(ArtifactName).$(buildConfiguration).$(buildPlatform)'

- task: PublishPipelineArtifact@1
  displayName: 'Copy VPack Manifest to Drop'
  inputs:
    targetPath: $(XES_VPACKMANIFESTDIRECTORY)
    artifactName: $(ArtifactName).$(buildConfiguration).$(buildPlatform)

- task: PkgESFCIBGit@12
  displayName: 'Package ES - Submit Files to Git'
  inputs:
    configPath: 'GitCheckinConfigs/GitCheckin.json'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)'
    prTimeOut: 5
    paToken: '$(patRef)'
