#Your build pipeline references an undefined variable named ‘BUILDCONFIGURATION’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘BUILDPLATFORM’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rr)

trigger:
- main

variables:
  ArtifactName: 'NXT3Shift_Artifacts'
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Debug'

steps:
- task: PackageES.pkges-vpack-task.pkges-vpack-task.PkgESVPack@12
  displayName: 'PkgESVPack '
  inputs:
    sourceDirectory: '$(Build.ArtifactStagingDirectory)'
    description: '$(ArtifactName).$(buildConfiguration).$(buildPlatform)'
